---
title: "Le Plomb Morgane"
format: html
editor: visual
---

## 1.1

```{r}
#| message: false
#| warning: false
here::i_am("grades-eval.Rproj")
library(here)
library(ggplot2)
library(vroom)
library(dplyr)
library(tidyr)
```

### 1 

```{r}
data <- vroom(here("data","courses.csv"))
```

### 2 

```{r}
data |> 
  mutate(
    `course name` = course,
    identifier = course_id,
    trimester = trimester,
    `number of exams` = nb_grades
  ) |>
  select(`course name`, identifier, trimester, `number of exams`) |>
  knitr::kable()
```


```{r}
courses <- data
```

### 3 

```{r}
students <- vroom(here("data","students.csv"))

spec(students)

students <- vroom(here("data","students.csv"), 
                  col_types = cols(
                    id = col_double(),
                       group = col_double(),
                       birth_date = col_date(format = "%Y-%m-%d"),
                       sex = col_factor(),
                       .delim = ","
                       ))

students |> summarise(
  birth_class = class(birth_date),
  sex_class = class(sex),
  group_class = class(group),
  id_class = class(id)
)
```

The birth_date column of the students data frame is of class  `r class(students |> pull(birth_date))`.

The sex column is of class  `r class(students |> pull(sex))`.

The group column is of class  `r class(students |> pull(group))`.

The id column is of class  `r class(students |> pull(id))`.

### 4 

```{r}
grades <- vroom(here("data","grades.csv"),
                delim = "|",
                na = "*",)
```
## 2 

### 5 

```{r}
students |>
  summarise(n = n(), .by = group) |>
  ggplot(aes(x = group, y = n)) +
  geom_col() +
  labs(
    x = "group",
    y = "number of students"
  ) +
  theme_minimal()
```

### 6 

```{r}
students |>
  ggplot(aes(x = group, fill = sex)) +
  geom_bar(position = "fill") +
  labs(
    x = "group",
    fill = "sex"
  ) +
  theme_minimal()
```

### 7 

```{r}
library(lubridate)

students_age <- students |>
  mutate(
    age = round(time_length(today() - birth_date, unit = "year"))
  )

students_age |>
  ggplot(aes(x = age)) +
  geom_histogram(binwidth = 1) +
  labs(
    x = "age"
  ) +
  theme_minimal()
```
### 8 

```{r}
table <- students_age |>
  summarise(
    median_age = as.integer(median(age)),
    .by = group
  )

table |>
  knitr::kable()
```

